### ISSUE TITLE
Identify/edit citations

### ISSUE THREAD

**Issue by lindsayplatt** [padilla410/lake-temp-lstm-static-data-release#10]
Need Winslow et al 2017, but what else?

**Comment by padilla410** [comment]
Later today I will doc what I referenced in my recent data release and why. I suspect we will want to use some of those papers and then @AndyMcAliley can fill in the rest.

Andy, for your reference, having thorough references in the data release is helpful because then you can save time in the write up of the process description.

**Comment by lindsayplatt** [comment]
NLDAS & GLM v3:

https://github.com/USGS-R/mntoha-data-release/blob/d94f73d3a09ddc6f43648b43f299529008ea9356/in_text/text_04_inputs.yml#L9-L22

**Comment by lindsayplatt** [comment]
For the GCM driver data, do we cite GDP? Or the dataset itself? There isn't a great citation for the dataset itself but I can find one for GDP

**Comment by padilla410** [comment]
NLDAS Citation reference [here](https://github.com/jordansread/lakesurf-data-release/blob/1745894c991df8ed2eec39a8040dc1f0db046f60/in_text/text_data_release.yml#L36-L41)

**Comment by padilla410** [comment]
A list of citations from the MO lake release ([SB](https://www.sciencebase.gov/catalog/item/63659da3d34ebe442507d10b) and [github](https://github.com/padilla410/lake-temp-mo-data-release/blob/main/remake.yml))

* [Mitchell et al, 2004](https://github.com/padilla410/lake-temp-mo-data-release/blob/main/in_text/text_data_release.yml#L35-L39)
* [Winslow et al, 2017](https://github.com/padilla410/lake-temp-mo-data-release/blob/main/in_text/text_data_release.yml#L40-L45)
* [Hipsey et al, 2019](https://github.com/padilla410/lake-temp-mo-data-release/blob/main/in_text/text_data_release.yml#L46-L51)
* [Read et al, 2019](https://github.com/padilla410/lake-temp-mo-data-release/blob/main/in_text/text_data_release.yml#L58-L63)
* [Read et al, 2021](https://github.com/padilla410/lake-temp-mo-data-release/blob/main/in_text/text_data_release.yml#L52-L57)
* [Willard et al, 2022](https://github.com/padilla410/lake-temp-mo-data-release/blob/main/in_text/text_data_release.yml#L64-L69)

**Comment by lindsayplatt** [comment]
For me, later this week:

```
library(dplyr)

# In the end, we need to order all of these citations alphabetically and then
# by year. If you take them all and paste into a `cites.yml`, you can use this
# to figure out the order.

x <- yaml::yaml.load_file('cites.yml')
all_authors <- lapply(y, `[[`, 'authors')
lead_authors <- unlist(purrr::map(all_authors, purrr::pluck, 1))
lead_authors_lastname_list <- stringr::str_split(lead_authors, " ")
lead_authors_lastname <- unlist(purrr::map(lead_authors_lastname_list, tail, 1))

pub_years <- unlist(lapply(y, `[[`, 'pubdate'))
titles <- unlist(lapply(y, `[[`, 'title'))
titles_first_word_list <- stringr::str_split(titles, " ")
titles_first_word <- unlist(purrr::map(titles_first_word_list, head, 1))

author_year_title <- paste(lead_authors_lastname, pub_years, titles_first_word, sep = "_")
author_year_title[order(author_year_title)]
```

**Comment by lindsayplatt** [comment]
Need to add https://github.com/DOI-USGS/ncdfgeom

**Comment by lindsayplatt** [comment]
Here are the cites I am going to include after combining through the current state of the metadata (in order that the content they are being referenced by appears in `in_text/text_data_release.yml`):

- Kratzert et al., 2019 - EA-LSTM model
- Hipsey et al., 2019 - GLM model
- Mitchell et al., 2004 - NLDAS dataset
- Notaro et al., 2018 - GCM dataset
- NHDPlus HR; USGS, 2017 - the NHDHR site ids and locations
- Hollister et al., 2021 - elevation data download package
- Soranno and Cheruvelil, 2017 - LAGOS-NE for clarity data
- Winslow et al., 2017 - used for lake id xwalk + methods for munging driver data
- Read et al., 2021 - methods for formatting NLDAS & some GCM data
- Blodgett, 2019 - ncdfgeom for DSG formatting of preds NetCDF files
- Eaton et al., 1995 - used for a subset of the `height_[temps]`, `vol_[temps]`, and `days_[temps]` metrics
- Wismer and Christie 1987 - used for a subset of the `height_[temps]`, `vol_[temps]`, and `days_[temps]` metrics + `spring_days_in_10.5_15.5` + `date_over_[temp]`
- Fang et al., 2004 - used for a subset of the `height_[temps]`, `vol_[temps]`, and `days_[temps]` metrics
- Christie and Regier, 1988 - used for a subset of the `height_[temps]`, `vol_[temps]`, and `days_[temps]` metrics
- Cline et al., 2013 - used for a subset of the `height_[temps]`, `vol_[temps]`, and `days_[temps]` metrics
- Casselman, 2002 - used for a subset of the `height_[temps]`, `vol_[temps]`, and `days_[temps]` metrics
- Countant, 1977 - used for a subset of the `height_[temps]`, `vol_[temps]`, and `days_[temps]` metrics
- Busch et al., 1975 - used for `post_ice_warm_rate`
- Madenijan et al., 1996 - also used for `post_ice_warm_rate`
- Read et al. 2011 - for `SmetaTopD_mean` and `SmetaBotD_mean`
- Read et al., 2015 - geoknife for GCM download
- Willard et al. 2022 - descriptions of temp and lake attribute data assembling
- Kingma et al., 2015 - the Adam optimizer for EALSTM
