### ISSUE TITLE
Distinguish "contemporary period" for EA-LSTM and GLM

### ISSUE THREAD

**Issue by lindsayplatt** [padilla410/lake-temp-lstm-static-data-release#17]
NLDAS drivers are available from `1979-01-02` to `2022-04-11`. EA-LSTM had a spin-up of 100 days before making predictions, while GLM  used a "burn-in" period of 1 year and "burn-out" period of ~100 days. Thus, their predictions in the contemporary period cover slightly different date ranges. Incorporate these into the abstract and other metadata as necessary.

EA-LSTM predictions start on `1979-04-12` and end on `2022-04-11`, while GLM predictions start on `1980-01-01` and end on `2021-12-31`.

**Comment by AndyMcAliley** [comment]
"burn-in" and "spin-up" basically mean the same thing. I'd be comfortable changing the language used for the EA-LSTM to "burn-in".

**Comment by hcorson-dosch-usgs** [comment]
Looks good. Technically 364 days of burn-in, 101 of burn out for GLM NLDAS

**Comment by lindsayplatt** [comment]
@hcorson-dosch-usgs would you be OK with using "spin-up" and "spin-down" instead? That is more intuitive to me than burn-in/burn-out

**Comment by hcorson-dosch-usgs** [comment]
Yes, that's fine with me

**Comment by lindsayplatt** [comment]
Closed by #27
