### ISSUE TITLE
Write abstract

### ISSUE THREAD

**Issue by lindsayplatt** [padilla410/lake-temp-lstm-static-data-release#2]

**Comment by lindsayplatt** [comment]
> This study was funded by the [see #7]. Access to computing facilities was provided by USGS Core Science Analytics and Synthesis Advanced Research Computing, USGS Tallgrass Supercomputer (https://doi.org/10.5066/P9XE7ROJ).

**Comment by AndyMcAliley** [comment]
> note for later: GLM-NLDAS = 12,688 lakes; GLM-GCM = 11,715 lakes; LSTM = ??? lakes

See discussion on how many lakes to include [here](https://github.com/padilla410/lake-temp-lstm-static-data-release/pull/12#discussion_r1069669559).
