### ISSUE TITLE
When/why does `kw = Inf`?

### ISSUE THREAD

**Issue by lindsayplatt** [padilla410/lake-temp-lstm-static-data-release#22]
There is one site with an `Inf` clarity value ... could be an issue with secchi = 0 and dividing `1.7/0`? Do we filter?

```
library(tidyverse)

lake_metadata <- read_csv('out_data/lake_metadata.csv')

max(lake_metadata$clarity, na.rm=TRUE)
[1] Inf

lake_metadata %>% filter(clarity == Inf) %>% pull(site_id)
[1] "nhdhr_86282143"

```

**Comment by lindsayplatt** [comment]
@AndyMcAliley and @hcorson-dosch-usgs can you add a comment below about how this may or may not have impacted your models? I think I can report the max non-infinite value in the metadata and include a little note that this one site is `Inf` likely due to a reported secchi depth of `0`.

**Comment by hcorson-dosch-usgs** [comment]
That site isn't among the glm-modelable sites for which we ran NLDAS and GCM models, so the `Inf` clarity value wouldn't have affected the model runs:
```r
> length(unique(p1_lake_cell_tile_xwalk_df$site_id))
[1] 12299
> "nhdhr_86282143" %in% p1_lake_cell_tile_xwalk_df$site_id
[1] FALSE
> length(unique(p1_lake_to_state_xwalk_df$site_id))
[1] 12864
> "nhdhr_86282143" %in% p1_lake_to_state_xwalk_df$site_id
[1] FALSE
```

**Comment by lindsayplatt** [comment]
Excellent! Thanks!!

**Comment by lindsayplatt** [comment]
OK, here's how I've talked about this site:

> attr-label: clarity
      attr-def: >- 
        The lake's clarity represented as the extinction coefficient, k. Single value for each 
        lake derived from either averaged time-varying predictions of k or calculated from secchi 
        depth using k=1.7/secchi. Note that the clarity value for site "nhdhr_86282143" is `Inf`  
        (likely due to a `0` value for secchi depth) and this site only has EA-LSTM predictions
        available. Since the EA-LSTM model used in this study did not use clarity as an input, 
        this `Inf` clarity value was deemed inconsequential for the modeling results.
      attr-defs: >-
        Variety of secchi depths and k values were synthesized in this data release, including from LAGOS, 
        Landsat, and the Water Quality Portal.
