### ISSUE TITLE
NLDAS meteo zip is >40 GB?!

### ISSUE THREAD

**Issue by lindsayplatt** [padilla410/lake-temp-lstm-static-data-release#23]
OK, so we have 8,802 NLDAS CSV driver files to zip up. My zip is not complete and it is currently at 43 GB. I assume we didn't have a problem before because our footprint was smaller.  

Ideas for the best way to split? The files are named as `NLDAS_time[VAL]_x[VAL]_y[VAL].csv`, where `time[VAL]` has only one unique value, `x[VAL]` has 187 unique values, and `y[VAL]` has 138 unique values.

Unfortunately, they would need to be split into at least 5 different files to fit under the 10 GB limit. Is there some other compression option that you all know how to do? We could convert from CSV to feather, but that is not one of the filetypes that SB likes.

@AndyMcAliley @hcorson-dosch-usgs @padilla410

**Comment by lindsayplatt** [comment]
I should have looked earlier rather than letting it just build forever but the final zip would be ~100 GB based on the CSVs in the folder

**Comment by AndyMcAliley** [comment]
I don't know of compression options that would get us from 40 GB to under 10 GB. Converting to netCDF may or may not get us under 10 GB, and converting to netCDF would take some time. The best idea I have is to split up the files by x and y, e.g. `NLDAS_x1-20_y1-20.zip`, `NLDAS_x20-40_y1-20.zip`, `NLDAS_x40-60_y1-20.zip`, `NLDAS_x1-20_y20-40.zip`, `NLDAS_x20-40_y20-40.zip`, `NLDAS_x40-60_y20-40.zip`. The MNTOHA data release did a similar thing: https://www.sciencebase.gov/catalog/item/5e5d0b96e4b01d50924f2b34

**Comment by lindsayplatt** [comment]
Really tried to keep the number of top-level files to a minimum, but I agree that the easiest way would just be to split up the files. 

Would anyone be interested in finishing this code up to add a column called `nldas_grp` that splits the files into ~8 groups? Would be great to do this in the next couple of hours. @AndyMcAliley @padilla410 @hcorson-dosch-usgs

I got a start but there's a lot of other stuff to do to finish this up. I think it would be fairly simple to add a new column to that top tibble but will take some logic-ing through. The second code block has 30 example filenames and the function I wrote to extract their x/y values.

```r
library(tidyverse)
tibble(fn = meteo_fls) %>%
  mutate(xval = extract_val(fn, 'x'),
         yval = extract_val(fn, 'y')) 
# TODO add a `nldas_grp` column using the x/y values into 8 groups

```

```r
extract_val <- function(str, x_or_y = c('x', 'y')) {
  x_regex <- 'NLDAS_time\\[0.379366]_x\\[|\\]_y\\[([0-9]{,3})\\].csv'
  y_regex <- 'NLDAS_time\\[0.379366]_x\\[([0-9]{,3})\\]_y\\[|\\].csv'
  
  regex <- switch(x_or_y,
                  x = x_regex,
                  y = y_regex)
  
  split_list <- strsplit(str, regex)
  vals <- map(split_list, pluck, 2) %>% reduce(c) %>% as.numeric()
  return(vals)
}


meteo_fls <- c("NLDAS_time[0.379366]_x[210]_y[186].csv", "NLDAS_time[0.379366]_x[292]_y[174].csv",
               "NLDAS_time[0.379366]_x[257]_y[162].csv", "NLDAS_time[0.379366]_x[205]_y[149].csv",
               "NLDAS_time[0.379366]_x[277]_y[95].csv", "NLDAS_time[0.379366]_x[311]_y[122].csv",
               "NLDAS_time[0.379366]_x[242]_y[175].csv", "NLDAS_time[0.379366]_x[273]_y[161].csv",
               "NLDAS_time[0.379366]_x[300]_y[170].csv", "NLDAS_time[0.379366]_x[182]_y[191].csv",
               "NLDAS_time[0.379366]_x[325]_y[169].csv", "NLDAS_time[0.379366]_x[231]_y[180].csv",
               "NLDAS_time[0.379366]_x[284]_y[161].csv", "NLDAS_time[0.379366]_x[289]_y[103].csv",
               "NLDAS_time[0.379366]_x[245]_y[111].csv", "NLDAS_time[0.379366]_x[188]_y[181].csv",
               "NLDAS_time[0.379366]_x[244]_y[181].csv", "NLDAS_time[0.379366]_x[329]_y[124].csv",
               "NLDAS_time[0.379366]_x[278]_y[86].csv", "NLDAS_time[0.379366]_x[229]_y[156].csv",
               "NLDAS_time[0.379366]_x[188]_y[154].csv", "NLDAS_time[0.379366]_x[297]_y[156].csv",
               "NLDAS_time[0.379366]_x[268]_y[75].csv", "NLDAS_time[0.379366]_x[171]_y[165].csv",
               "NLDAS_time[0.379366]_x[218]_y[172].csv", "NLDAS_time[0.379366]_x[194]_y[151].csv",
               "NLDAS_time[0.379366]_x[167]_y[143].csv", "NLDAS_time[0.379366]_x[180]_y[138].csv",
               "NLDAS_time[0.379366]_x[248]_y[81].csv", "NLDAS_time[0.379366]_x[189]_y[153].csv"
)
```

**Comment by lindsayplatt** [comment]
I think I've got it:

```r
write_file <- function(grp_data) {
  sprintf('myfile/path/grp_%s_data.zip', unique(grp_data$grp_n))
  files_to_zip <- grp_data %>% select(-grp_n, -xyval) %>% pull(fn)
  return(files_to_zip)
}

ngrps <- 8
x <- val_df %>% 
  unite(xyval, xval, yval) %>% 
  distinct() %>% 
  arrange(xyval) %>% 
  mutate(grp_n = cut(seq_along(xyval), ngrps, labels = FALSE)) %>% 
  split(.$grp_n) %>% 
  map(~write_file(.))
```

**Comment by hcorson-dosch-usgs** [comment]
Sorry, Lindsay -- somehow I missed this notification. Nice work on that solution!

**Comment by lindsayplatt** [comment]
Added an additional column to the `lake_metadata.csv` in order to describe which ZIP the NLDAS meteo files are in called `driver_nldas_zipfile`.
