### ISSUE TITLE
List data files to include

### ISSUE THREAD

**Issue by lindsayplatt** [padilla410/lake-temp-lstm-static-data-release#3]
Write out filenames, types, and what they contain

**Comment by lindsayplatt** [comment]
First pass at this:

File Name | Description/comments/questions
-- | --
lake_metadata.csv | include column for whether the lake is included in each model w T/F?
lake_locations.zip | Should just be lat/long?
lake_config.nml | Should just be the one file I think … (don't need the config.json that is used in others)?
lake_temperature_observations.zip |  
meteorological_inputs_nldas.zip |  
meteorological_inputs_gcm.zip |  
lake_temp_preds_glm_nldas.zip |  
lake_temp_preds_glm_gcm.zip |  
lake_temp_preds_lstm_nldas.zip |  
lake_temp_metrics_glm_nldas.csv |  
lake_temp_metrics_glm_gcm.csv |

**Comment by lindsayplatt** [comment]
Let's list out what lake attributes we are actually using so that we can include in a single metadata file!

**Comment by AndyMcAliley** [comment]
Which lake attributes Andy uses, to be merged with Lindsay's table and included in a single metadata file (and which file in model-prep we can find them)

Lake attribute | `model-prep` origin file
-- | --
Max depth | ????

**Comment by lindsayplatt** [comment]
The list I initially wrote did not include any evaluation files. We did include evaluation-specific files in [the MN TOHA release](https://www.sciencebase.gov/catalog/item/5e5c1b4fe4b01d50924f27e1) but not in [the previous Midwest release](https://www.sciencebase.gov/catalog/item/5db761e7e4b0b0c58b5a4978).

**Comment by AndyMcAliley** [comment]
Do we have a ready-made way to match lakes to states?

**Comment by lindsayplatt** [comment]
Yes! That crosswalk exists here: https://github.com/USGS-R/lake-temperature-model-prep/blob/main/2_crosswalk_munge.yml#L167

**Comment by AndyMcAliley** [comment]
> The list I initially wrote did not include any evaluation files. We did include evaluation-specific files in [the MN TOHA release](https://www.sciencebase.gov/catalog/item/5e5c1b4fe4b01d50924f27e1) but not in [the previous Midwest release](https://www.sciencebase.gov/catalog/item/5db761e7e4b0b0c58b5a4978).

I did a fair bit of initial evaluation work, but I don't have ready-made eval files. Just one that gives three overall performance stats (RMSE, median RMSE over all lakes, mean RMSE over all lakes).

**Comment by lindsayplatt** [comment]
File Name | Description/comments/questions
-- | --
lake_metadata.csv | include column for whether the lake is included in each model w T/F?
lake_locations.zip | Spatial zip
lake_temperature_observations.zip |  
meteorological_inputs_nldas.zip |  
meteorological_inputs_gcm.zip |  
lake_temp_preds_glm_nldas.nc |  
lake_temp_preds_glm_gcm.nc |  
lake_temp_preds_lstm_nldas.nc |  
lake_temp_metrics_glm_nldas.csv |  
lake_temp_metrics_glm_gcm.csv |

**Comment by lindsayplatt** [comment]
I'm now wondering how necessary the meteorological inputs are to include ... ?

**Comment by lindsayplatt** [comment]
For now, logging my scripts/progress on each of the files here. Pretty good progress but still have some work to do on the meteo files.

```r
library(sf)
library(tidyverse)

##### lake_metadata.csv #####

# This file was sent by Andy
lstm_metadata <- read_csv('in_data/lake_metadata_lstm.csv') %>% 
  select(site_id, area, elevation, state, lstm_group, lstm_predictions)

lake_centroids_sf <- readRDS('../lake-temperature-model-prep/2_crosswalk_munge/out/centroid_lakes_sf.rds')
lake_gnis_names <- readRDS('../lake-temperature-model-prep/2_crosswalk_munge/out/gnisname_nhdhr_xwalk.rds')
lake_depths <- readRDS('../lake-temperature-model-prep/7_config_merge/out/nml_lake_depth_values.rds') %>% ungroup() # Only available for ~15k lakes

lake_metadata <- lake_centroids_sf %>% 
  st_coordinates() %>% 
  as_tibble() %>% 
  mutate(site_id = lake_centroids_sf$site_id) %>% 
  left_join(lake_gnis_names, by = "site_id") %>% 
  left_join(lake_depths, by = "site_id") %>% 
  # ADD LSTM-specific metadata
  left_join(lstm_metadata, by = "site_id") %>% 
  # Remove sites that don't have any LSTM predictions (those are outside of our scope)
  filter(lstm_predictions) %>% 
  # Rename and organize final columns
  select(site_id, 
         lake_name = GNIS_Name,
         state,
         centroid_lat = Y,
         centroid_lon = X,
         depth = lake_depth,
         area,
         elevation,
         ea_lstm_group = lstm_group)

# TODO: Still need to add these columns:
# NLDAS filepath (e.g. `readRDS('../lake-temperature-model-prep/7_config_merge/out/nml_meteo_fl_values.rds')`)
# GCM filepath (NA if none)
# EA-LSTM predictions available - T (all are true)
# GLM-NLDAS predictions available - T/F
# GLM-GCM predictions available - T/F

##### lake_hypsography.csv #####

# Lake hypsography CSV creation
H_A_list <- readRDS('../lake-temperature-model-prep/7_config_merge/out/nml_H_A_values.rds')
hypso_list <- purrr::map(H_A_list, function(H_A_df) {
  H_A_df %>% 
    mutate(depths = max(H) - H, areas = A) %>% 
    arrange(depths) %>% 
    select(depths, areas)
})
hypso_df <- purrr::map_df(hypso_list, ~as.data.frame(.x), .id="site_id")
write_csv(hypso_df, 'lake_hypsography.csv')

##### lake_locations.zip #####

lake_centroids_sf <- readRDS('../lake-temperature-model-prep/2_crosswalk_munge/out/centroid_lakes_sf.rds')
lstm_lakes <- read_csv('in_data/lake_metadata_lstm.csv') %>% filter(lstm_predictions) %>% pull(site_id)
lake_centroids_sf_lstm <- lake_centroids_sf %>% filter(site_id %in% lstm_lakes)
write_sf(lake_centroids_sf_lstm, 'lake_locations.shp')
shp_files <- sprintf('lake_locations.%s', c('shp', 'shx', 'dbf', 'prj'))
zip::zip('lake_locations.zip', files = shp_files)
file.remove(shp_files)

##### lake_temperature_observations.zip #####

temp_obs_all <- arrow::read_feather('../lake-temperature-model-prep/7b_temp_merge/out/temp_data_with_sources.feather') %>% 
  filter(date >= as.Date('1980-01-01')) %>% 
  select(-source_id)
length(unique(temp_obs_all$site_id)) # 8,965 lakes with at least one observation

temp_obs_fn <- 'lake_temperature_observations.csv'
write_csv(temp_obs_all, temp_obs_fn)
zip::zip('lake_temperature_observations.zip', files = temp_obs_fn)
file.remove(temp_obs_fn)

##### meteorological_inputs_nldas.zip #####

# TODO

##### meteorological_inputs_gcm.zip #####

# TODO

##### ACTUAL TEMP PREDICTIONS #####

# TODO: Hayley and Andy are working on these

##### lake_temperature_metrics_glm_nldas.csv #####

# Need to do this on Tallgrass
nldas_metrics <- read_csv('../lake-temperature-out/3_summarize/out/annual_metrics_glm3_pb0nldas.csv')
write_csv(nldas_metrics, 'lake_temperature_metrics_glm_nldas.csv')

##### lake_temperature_metrics_glm_gcm.csv #####

# Need to do this on Tallgrass
gcm_metrics <- read_csv('../lake-temperature-out/3_summarize/out/annual_metrics_glm3_pb0gcm.csv')
write_csv(gcm_metrics, 'lake_temperature_metrics_glm_gcm.csv')

##### lake_id_xwalk.csv #####

# TODO: Jordan made this file and shared on Slack. I need to find it
```

**Comment by lindsayplatt** [comment]
Working on defining the ids & deciding which to include:

- IADNR_ID = Iowa Department of Natural Resources
- IN_CLP_ID = Indiana Clean Lakes Program 
- IN_DNR_ID = 
- Iowa_ID = These [are supposedly from Iowa DNR](https://docs.google.com/document/d/1ZXvohYWoDIY29kZ4TDVBbRXG7XVJ1Bsj7JFDxZLx1DE/edit), but differ from the values in `IADNR_ID` and don't appear on [the IA DNR website](https://www.iowadnr.gov/idnr/Fishing/Where-to-Fish/Lakes-Ponds-Reservoirs/Lake-Details?lakeCode=AHQ91). There are 18 from this column that don't have a matching IADNR_ID
- ISRO_ID = 
- LAGOS_ID = 
- MGLP_ID = 
- MICORPS_ID = Michigan Clean Water Corps
- MNDOW_ID = 
- MO_USACE_ID = Missouri US Army Corps of Engineers
- Navico_ID = 
- NDGF_ID = 
- SD_ID = 
- UNDERC_ID = University of Notre Dame Environmental Research Center
- UNIV_MO_ID = University of Minnesota
- WBIC_ID = Wisconsin DNR's WaterBody Id Code
- WINSLOW_ID = An earlier release of modeled lake temperature data, Winslow et al 2017

**Comment by padilla410** [comment]
I think I can help with some of these, Lindsay

**Comment by padilla410** [comment]
> IOWA_ID = These [are supposedly from Iowa DNR](https://docs.google.com/document/d/1ZXvohYWoDIY29kZ4TDVBbRXG7XVJ1Bsj7JFDxZLx1DE/edit), but differ from the values in IADNR_ID and don't appear on [the IA DNR website](https://www.iowadnr.gov/idnr/Fishing/Where-to-Fish/Lakes-Ponds-Reservoirs/Lake-Details?lakeCode=AHQ91). There are 18 from this column that don't have a matching IADNR_ID

Yes, I see you found the metadata. These lakes were part of a data rescue attempt. I couldn't find any info about them on any publicly available website. Grace Wilkerson manually provided the lat/longs. I'm pretty sure the ones missing spatial info are supposed to be filtered out of the munged dataset.

IN_DNR = Indiana DNR ([metadata](https://docs.google.com/document/d/1LCJXAfhvuZPREobD1k4gzyy-IGagsu4ayLZhu1bDgxA/edit))

SD_ID = South Dakota Department of Environment and Natural Resources ([metadata](https://docs.google.com/document/d/1upz9twkX2Ry4sBLA4g06wHGrELOV0SL4yJ8y7KNl_Jw/edit))

**Comment by lindsayplatt** [comment]
OK, let's exclude the `Iowa_ID` column as they are likely only useful in our model prep pipeline and not for users of this data release.

**Comment by lindsayplatt** [comment]
See final list https://github.com/padilla410/lake-temp-lstm-static-data-release/pull/18#issuecomment-1429869652
