### ISSUE TITLE
Write process description, EA-LSTM

### ISSUE THREAD

**Issue by lindsayplatt** [padilla410/lake-temp-lstm-static-data-release#6]
Example here: https://github.com/jordansread/lakesurf-data-release/blob/main/in_text/text_data_release.yml#L784

**Comment by AndyMcAliley** [comment]
Another example is here: https://github.com/padilla410/lake-temp-mo-data-release/blob/1b453fc062bcf7dcd4d26fc722a43c1e357db0cb/in_text/text_data_release.yml#L447
