### ISSUE TITLE
Author affiliation for Jordan?

### ISSUE THREAD

**Issue by padilla410** [padilla410/lake-temp-lstm-static-data-release#9]
I am no longer able to list @jordansread as a USGS author on the IPDS record for this data release. Thoughts on the appropriate affiliation?

**Comment by lindsayplatt** [comment]
Hmmmm he was an employee when the work was completed. I'm going to go ask for advice in a MS channel

**Comment by padilla410** [comment]
I added Jordan using the following non-USGS affiliation: "US Geological Survey"
